// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/nt/oidb/oidbSvcTrpcTcp0xFE5_2/oidbSvcTrpcTcp0xfe5_2.proto

package oidbSvcTrpcTcp0xFE5_2

// Request message
type Request struct {
	Config *Config `protobuf:"bytes,1,opt"`
	_      [0]func()
}

// Config message
type Config struct {
	Config1 *Config1 `protobuf:"bytes,1,opt"`
	Config2 *Config2 `protobuf:"bytes,2,opt"`
	Config3 *Config3 `protobuf:"bytes,3,opt"`
	_       [0]func()
}

// Config1 message
type Config1 struct {
	GroupOwner  bool `protobuf:"varint,1,opt"`
	Field2      bool `protobuf:"varint,2,opt"`
	MemberMax   bool `protobuf:"varint,3,opt"`
	MemberCount bool `protobuf:"varint,4,opt"`
	GroupName   bool `protobuf:"varint,5,opt"`
	Field8      bool `protobuf:"varint,8,opt"`
	Field9      bool `protobuf:"varint,9,opt"`
	Field10     bool `protobuf:"varint,10,opt"`
	Field11     bool `protobuf:"varint,11,opt"`
	Field12     bool `protobuf:"varint,12,opt"`
	Field13     bool `protobuf:"varint,13,opt"`
	Field14     bool `protobuf:"varint,14,opt"`
	Field15     bool `protobuf:"varint,15,opt"`
	Field16     bool `protobuf:"varint,16,opt"`
	Field17     bool `protobuf:"varint,17,opt"`
	Field18     bool `protobuf:"varint,18,opt"`
	Question    bool `protobuf:"varint,19,opt"`
	Field20     bool `protobuf:"varint,20,opt"`
	Field22     bool `protobuf:"varint,22,opt"`
	Field23     bool `protobuf:"varint,23,opt"`
	Field24     bool `protobuf:"varint,24,opt"`
	Field25     bool `protobuf:"varint,25,opt"`
	Field26     bool `protobuf:"varint,26,opt"`
	Field27     bool `protobuf:"varint,27,opt"`
	Field28     bool `protobuf:"varint,28,opt"`
	Field29     bool `protobuf:"varint,29,opt"`
	Field30     bool `protobuf:"varint,30,opt"`
	Field31     bool `protobuf:"varint,31,opt"`
	Field32     bool `protobuf:"varint,32,opt"`
	Field5001   bool `protobuf:"varint,5001,opt"`
	Field5002   bool `protobuf:"varint,5002,opt"`
	Field5003   bool `protobuf:"varint,5003,opt"`
	_           [0]func()
}

// Config2 message
type Config2 struct {
	Field1 bool `protobuf:"varint,1,opt"`
	Field2 bool `protobuf:"varint,2,opt"`
	Field3 bool `protobuf:"varint,3,opt"`
	Field4 bool `protobuf:"varint,4,opt"`
	Field5 bool `protobuf:"varint,5,opt"`
	Field6 bool `protobuf:"varint,6,opt"`
	Field7 bool `protobuf:"varint,7,opt"`
	Field8 bool `protobuf:"varint,8,opt"`
	_      [0]func()
}

// Config3 message
type Config3 struct {
	Field5 bool `protobuf:"varint,5,opt"`
	Field6 bool `protobuf:"varint,6,opt"`
	_      [0]func()
}

// Response message
type Response struct {
	Groups []*Group `protobuf:"bytes,2,rep"`
}

// Group message
type Group struct {
	GroupUin int64      `protobuf:"varint,3,opt"`
	Info     *GroupInfo `protobuf:"bytes,4,opt"`
	_        [0]func()
}

// GroupInfo message
type GroupInfo struct {
	GroupOwner  *Member `protobuf:"bytes,1,opt"`
	MemberMax   int64   `protobuf:"varint,3,opt"`
	MemberCount int64   `protobuf:"varint,4,opt"`
	GroupName   string  `protobuf:"bytes,5,opt"`
	_           [0]func()
}

// Member message
type Member struct {
	Uid string `protobuf:"bytes,2,opt"`
	_   [0]func()
}
