// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/trpc/trpc.proto

package trpc

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// trpc.msg.register_proxy.RegisterProxy.PushParams
type TrpcPushParams struct {
	OnlineDevices       []*OnlineDevice      `protobuf:"bytes,4,rep"`
	GuildParams         *GuildParams         `protobuf:"bytes,6,opt"`
	ErrMsg              proto.Option[string] `protobuf:"bytes,7,opt"`
	GroupMsgStorageTime proto.Option[uint32] `protobuf:"varint,9,opt"`
}

type GuildParams struct {
	GuildFlag       proto.Option[uint32] `protobuf:"varint,1,opt"`
	GuildSwitchFlag proto.Option[uint32] `protobuf:"varint,2,opt"`
	_               [0]func()
}

type OnlineDevice struct {
	InstId        proto.Option[uint32] `protobuf:"varint,1,opt"`
	ClientType    proto.Option[uint32] `protobuf:"varint,2,opt"`
	State         proto.Option[uint32] `protobuf:"varint,3,opt"`
	PlatId        proto.Option[uint32] `protobuf:"varint,4,opt"`
	PlatType      proto.Option[string] `protobuf:"bytes,5,opt"`
	NewClientType proto.Option[uint32] `protobuf:"varint,6,opt"`
	DeviceName    proto.Option[string] `protobuf:"bytes,7,opt"`
	_             [0]func()
}

type SsoHeartBeat struct {
	Unknown1 proto.Option[int32]    `protobuf:"varint,1,opt"`
	Unknown2 *SsoHeartBeat_Unknown2 `protobuf:"bytes,2,opt"`
	Unknown3 proto.Option[int32]    `protobuf:"varint,3,opt"`
	Time     proto.Option[int64]    `protobuf:"varint,4,opt"`
	_        [0]func()
}

type UnRegister struct {
	Field1     proto.Option[int32]    `protobuf:"varint,1,opt"`
	Field3     proto.Option[int32]    `protobuf:"varint,3,opt"`
	DeviceInfo *UnRegister_DeviceInfo `protobuf:"bytes,2,opt"`
	_          [0]func()
}

type UnRegisterResp struct {
	Message proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type NTKickEvent struct {
	Uin   proto.Option[int64]  `protobuf:"varint,1,opt"`
	Tips  proto.Option[string] `protobuf:"bytes,3,opt"`
	Title proto.Option[string] `protobuf:"bytes,2,opt"`
	_     [0]func()
}

type SsoInfoSyncReqBody struct {
	Tag                  proto.Option[int32]              `protobuf:"varint,1,opt"` //735
	RandomSeq            proto.Option[int32]              `protobuf:"varint,2,opt"`
	ReqType              proto.Option[int32]              `protobuf:"varint,4,opt"` //2
	LastGroupMessageTime proto.Option[int32]              `protobuf:"varint,5,opt"`
	SsoInfoSyncC2C       *SsoInfoSyncReqBody_MessageTime  `protobuf:"bytes,6,opt"`
	MetaDataList         *SsoInfoSyncReqBody_MetaDataList `protobuf:"bytes,8,opt"`
	DeviceInfo           *SsoInfoSyncReqBody_DeviceInfo   `protobuf:"bytes,9,opt"`
	Unknown10            *SsoInfoSyncReqBody_Unknown10    `protobuf:"bytes,10,opt"`
	Unknown11            *SsoInfoSyncReqBody_Unknown11    `protobuf:"bytes,11,opt"`
	_                    [0]func()
}

type SsoInfoSyncRespBody struct {
	RetData *SsoInfoSyncRespBody_Data `protobuf:"bytes,7,opt"`
	_       [0]func()
}

type SsoHeartBeat_Unknown2 struct {
	Unknown1 proto.Option[int32] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type UnRegister_DeviceInfo struct {
	BrandModel     proto.Option[string] `protobuf:"bytes,1,opt"`
	Device         proto.Option[string] `protobuf:"bytes,2,opt"`
	VersionRelease proto.Option[string] `protobuf:"bytes,3,opt"`
	Brand          proto.Option[string] `protobuf:"bytes,4,opt"`
	ProductUser    proto.Option[string] `protobuf:"bytes,5,opt"`
	_              [0]func()
}

type SsoInfoSyncReqBody_MessageTime struct {
	Unknown_1              *SsoInfoSyncReqBody_MessageTime_UnknownTime `protobuf:"bytes,1,opt"`
	LastPrivateMessageTime proto.Option[int32]                         `protobuf:"varint,2,opt"`
	Unknown_3              *SsoInfoSyncReqBody_MessageTime_UnknownTime `protobuf:"bytes,3,opt"`
	_                      [0]func()
}

type SsoInfoSyncReqBody_MetaDataList struct {
	// type = 46, value=lastOnlineTime
	// type = 283, value=0
	LastDoData []*SsoInfoSyncReqBody_MetaDataList_MetaData `protobuf:"bytes,1,rep"`
}

type SsoInfoSyncReqBody_DeviceInfo struct {
	Guid      proto.Option[string]                     `protobuf:"bytes,1,opt"`
	Unknown_2 proto.Option[int32]                      `protobuf:"varint,2,opt"` // 0
	ApkCode   proto.Option[string]                     `protobuf:"bytes,3,opt"`
	Unknown_4 proto.Option[int32]                      `protobuf:"varint,4,opt"` // 1
	Unknown_5 proto.Option[int32]                      `protobuf:"varint,5,opt"` //2052
	PhoneInfo *SsoInfoSyncReqBody_DeviceInfo_PhoneInfo `protobuf:"bytes,6,opt"`
	Unknown_7 proto.Option[int32]                      `protobuf:"varint,7,opt"` // 0
	Unknown_8 proto.Option[int32]                      `protobuf:"varint,8,opt"` // 5
	// 0代表保守上线(已经有另一个设备登录就弃权)，1代表激进上线(已经有另一个设备就踹掉对方)
	ReLogin    proto.Option[int32]                       `protobuf:"varint,9,opt"`
	Unknown_10 *SsoInfoSyncReqBody_DeviceInfo_Unknown_10 `protobuf:"bytes,10,opt"`
	Unknown_11 proto.Option[int32]                       `protobuf:"varint,11,opt"` // 0
	_          [0]func()
}

type SsoInfoSyncReqBody_Unknown10 struct {
	Unknown_1 proto.Option[int32] `protobuf:"varint,1,opt"` // 0
	Unknown_2 proto.Option[int32] `protobuf:"varint,2,opt"` // 1
	_         [0]func()
}

type SsoInfoSyncReqBody_Unknown11 struct {
	Unknown_1 proto.Option[int32] `protobuf:"varint,1,opt"` // 0
	Unknown_2 proto.Option[int32] `protobuf:"varint,2,opt"` // 1
	Unknown_3 proto.Option[int32] `protobuf:"varint,3,opt"` // 0
	_         [0]func()
}

type SsoInfoSyncReqBody_MessageTime_UnknownTime struct {
	Time proto.Option[int32] `protobuf:"varint,1,opt"` //can set 0
	_    [0]func()
}

type SsoInfoSyncReqBody_MetaDataList_MetaData struct {
	Type  proto.Option[int32] `protobuf:"varint,1,opt"`
	Value proto.Option[int32] `protobuf:"varint,2,opt"`
	_     [0]func()
}

type SsoInfoSyncReqBody_DeviceInfo_PhoneInfo struct {
	BrandAndModel  proto.Option[string] `protobuf:"bytes,1,opt"`
	Device         proto.Option[string] `protobuf:"bytes,2,opt"`
	VersionRelease proto.Option[string] `protobuf:"bytes,3,opt"`
	Brand          proto.Option[string] `protobuf:"bytes,4,opt"`
	Linux          proto.Option[string] `protobuf:"bytes,5,opt"`
	_              [0]func()
}

type SsoInfoSyncReqBody_DeviceInfo_Unknown_10 struct {
	Unknown_1 proto.Option[int32] `protobuf:"varint,1,opt"` // 1
	Unknown_2 proto.Option[int32] `protobuf:"varint,2,opt"` // 1
	_         [0]func()
}

type SsoInfoSyncRespBody_Data struct {
	Message proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}
