// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/database/database_record.proto

package database

type DatabaseRecord struct {
	Video    *DatabaseVideo `protobuf:"bytes,1,opt"`
	Image    *DatabaseImage `protobuf:"bytes,2,opt"`
	Register *DataRegister  `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type DataRegister struct {
	ExpiredTime uint32 `protobuf:"varint,1,opt"`
	_           [0]func()
}

type DatabaseVideo struct {
	Md5       []byte `protobuf:"bytes,1,opt"`
	ThumbMd5  []byte `protobuf:"bytes,2,opt"`
	Size      uint32 `protobuf:"varint,3,opt"`
	ThumbSize uint32 `protobuf:"varint,4,opt"`
	Name      string `protobuf:"bytes,5,opt"`
	Uuid      []byte `protobuf:"bytes,6,opt"`
}

type DatabaseImage struct {
	Md5          []byte `protobuf:"bytes,1,opt"`
	Sha1         []byte `protobuf:"bytes,5,opt"`
	Size         uint32 `protobuf:"varint,2,opt"`
	ImageId      string `protobuf:"bytes,3,opt"`
	Path         string `protobuf:"bytes,4,opt"`
	Domain       string `protobuf:"bytes,9,opt"`
	Query        string `protobuf:"bytes,10,opt"`
	Width        uint32 `protobuf:"varint,6,opt"`
	Height       uint32 `protobuf:"varint,7,opt"`
	BusinessType uint32 `protobuf:"varint,8,opt"`
	ImageType    uint32 `protobuf:"varint,11,opt"`
}
