// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/nt/oidb/oidbSvcTrpcTcp0x8FC_2/oidbSvcTrpcTcp0x8fc_2.proto

package oidbSvcTrpcTcp0x8FC_2

type Body struct {
	TargetUid    string `protobuf:"bytes,1,opt"`
	SpecialTitle string `protobuf:"bytes,5,opt"`
	ExpiredTime  int32  `protobuf:"zigzag32,6,opt"`
	UinName      string `protobuf:"bytes,7,opt"`
	TargetName   string `protobuf:"bytes,8,opt"`
	_            [0]func()
}

type Request struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	Body     *Body  `protobuf:"bytes,3,opt"`
	_        [0]func()
}
