// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/cmd0x543/cmd0x543.proto

package cmd0x543

type Body struct {
	Data *Data `protobuf:"bytes,9,opt"`
	_    [0]func()
}

type Data struct {
	Account *Account `protobuf:"bytes,11,opt"`
	_       [0]func()
}

type Account struct {
	Uid string `protobuf:"bytes,1,opt"`
	_   [0]func()
}
