// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/nt/oidb/oidbSvcTrpcTcp0xFD4_1/oidbSvcTrpcTcp0xfd4_1.proto

package oidbSvcTrpcTcp0xFD4_1

// Request message
type Request struct {
	Count         int32   `protobuf:"varint,2,opt"`
	Field7        int32   `protobuf:"varint,7,opt"`
	ContinueToken []byte  `protobuf:"bytes,5,opt"`
	Field6        int64   `protobuf:"varint,6,opt"`
	Body          []*Body `protobuf:"bytes,10001,rep"`
	Field10002    []int64 `protobuf:"varint,10002,rep"`
	Field10003    int64   `protobuf:"varint,10003,opt"`
	Mode          int32   `protobuf:"varint,4,opt"`
}

// Body message
type Body struct {
	Type   int64       `protobuf:"varint,1,opt"`
	Number *OidbNumber `protobuf:"bytes,2,opt"`
	_      [0]func()
}

// OidbNumber message
type OidbNumber struct {
	Numbers []int64 `protobuf:"varint,1,rep"`
}

// Response message
type Response struct {
	DisplayFriendCount int64         `protobuf:"varint,3,opt"`
	Timestamp          int64         `protobuf:"varint,6,opt"`
	SelfUin            int64         `protobuf:"varint,7,opt"`
	ContinueToken      []byte        `protobuf:"bytes,2,opt"`
	Friends            []*OidbFriend `protobuf:"bytes,101,rep"`
	Groups             []*OidbGroup  `protobuf:"bytes,102,rep"`
}

// OidbFriend message
type OidbFriend struct {
	Uid        string              `protobuf:"bytes,1,opt"`
	Uin        int64               `protobuf:"varint,3,opt"`
	Additional []*FriendAdditional `protobuf:"bytes,10001,rep"`
}

// ContinueToken message
type ContinueToken struct {
	Uin int64 `protobuf:"varint,1,opt"`
	_   [0]func()
}

// OidbGroup message
type OidbGroup struct {
	Name string `protobuf:"bytes,2,opt"`
	Id   int32  `protobuf:"varint,1,opt"`
	_    [0]func()
}

// FriendAdditional message
type FriendAdditional struct {
	Type   int64         `protobuf:"varint,1,opt"`
	Layer1 *FriendLayer1 `protobuf:"bytes,2,opt"`
	_      [0]func()
}

// FriendLayer1 message
type FriendLayer1 struct {
	Properties []*FriendProperty `protobuf:"bytes,2,rep"`
}

// FriendProperty message
type FriendProperty struct {
	Code  int64  `protobuf:"varint,1,opt"`
	Value string `protobuf:"bytes,2,opt"`
	_     [0]func()
}
