// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/nt/oidb/partner/partner.proto

package partner

type Request struct {
	Type    string `protobuf:"bytes,1,opt"`
	Uid     string `protobuf:"bytes,2,opt"`
	Id      string `protobuf:"bytes,3,opt"`
	SubType string `protobuf:"bytes,4,opt"`
	_       [0]func()
}
